# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6faa9b713c3c55e0bfc730d06b0e11c436a2e8b78009ab6ad00924b56702537c5f93d5aab61b9f076856e45533b0e44f9438d1d6406709434a225535f592087e

test:
  secret_key_base: e296c7d8abbf24678d075906c946f13520304b901dd272bf01d4503e4e29b2283a10182325646c4dfb1a4a8bbfea3e6e30c7ae5757f34f57d69b19645c85b452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
